#include <vector>
#include <map>
#include <queue>
#include <algorithm>
#include <sstream>
#include <iostream>
#include <cmath>
#include <cstdlib>
#include <set>
#include <numeric>

#define FOR(A,B,C) for(int A=B;A<C;A++)
#define EFOR(A,B,C) for(int A=B;A<=C;A++)
#define RFOR(A,B,C) for(int A=B;A>=C;A--)
#define PB(A,B) A.push_back(B);
#define SORT(A) sort( A.begin(),A.end() )
#define ALL(A) A.begin(),A.end()
#define VI vector<int>
#define VS vector<string>
#define VD vector<double>
#define VB vector<bool>
#define SZ(A) int(A.size())
#define LL long long

using namespace std;

int chk[4]={1,3,4,6};

class CubeColoring {
public:
	long long theCount(vector <string>);
};

long long CubeColoring::theCount(vector <string> colors) {
	int N=SZ(colors[0]);

//	Counts the number of possible colors for each vertex
	unsigned LL pos[8];
	memset(pos,0,sizeof(pos));
	vector< VB >adj(8,VB(N));

	FOR(row,0,8)
		FOR(col,0,N){
			if(colors[row][col]=='Y')
				++pos[row],adj[row][col]=1;
			else
				adj[row][col]=0;
		}

	unsigned LL ans=0;
	bool done[N];

//	Assigns color to each independent vertex
	FOR(i,0,N)
	FOR(j,0,N)
	FOR(k,0,N)
	FOR(l,0,N)
		if(adj[0][i] && adj[2][j] && adj[5][k] && adj[7][l]){
			FOR(all,0,4){
				memset(done,-1,sizeof(done));

/*	Checks if vertex has same color in the possible colors set & if it is present, then decrements the count.
	It also stores the removed colors to prevent repition.
	Each vertex effects only 3 vertices, therefore it should not decrement the uneffected vertex.	*/

				if(adj[chk[all]][i] && done[i] && all!=3)
					--pos[chk[all]],done[i]=0;
				if(adj[chk[all]][j] && done[j] && all!=2)
					--pos[chk[all]],done[j]=0;
				if(adj[chk[all]][k] && done[k] && all!=1) 
					--pos[chk[all]],done[k]=0;
				if(adj[chk[all]][l] && done[l] && all!=0)
					--pos[chk[all]],done[l]=0;
			}

			ans+=(pos[1]*pos[3]*pos[4]*pos[6]);

			FOR(all,0,4){
				memset(done,-1,sizeof(done));
				if(adj[chk[all]][i] && done[i] && all!=3)
					++pos[chk[all]],done[i]=0;
				if(adj[chk[all]][j] && done[j] && all!=2)
					++pos[chk[all]],done[j]=0;
				if(adj[chk[all]][k] && done[k] && all!=1) 
					++pos[chk[all]],done[k]=0;
				if(adj[chk[all]][l] && done[l] && all!=0)
					++pos[chk[all]],done[l]=0;
			}
		}

	return ans;
}
// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit 2.1.8 (beta) modified by pivanof
#include <iostream>
#include <string>
#include <vector>
using namespace std;
bool KawigiEdit_RunTest(int testNum, vector <string> p0, bool hasAnswer, long long p1) {
	cout << "Test " << testNum << ": [" << "{";
	for (int i = 0; int(p0.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << "\"" << p0[i] << "\"";
	}
	cout << "}";
	cout << "]" << endl;
	CubeColoring *obj;
	long long answer;
	obj = new CubeColoring();
	clock_t startTime = clock();
	answer = obj->theCount(p0);
	clock_t endTime = clock();
	delete obj;
	bool res;
	res = true;
	cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
	if (hasAnswer) {
		cout << "Desired answer:" << endl;
		cout << "\t" << p1 << endl;
	}
	cout << "Your answer:" << endl;
	cout << "\t" << answer << endl;
	if (hasAnswer) {
		res = answer == p1;
	}
	if (!res) {
		cout << "DOESN'T MATCH!!!!" << endl;
	} else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
		cout << "FAIL the timeout" << endl;
		res = false;
	} else if (hasAnswer) {
		cout << "Match :-)" << endl;
	} else {
		cout << "OK, but is it right?" << endl;
	}
	cout << "" << endl;
	return res;
}
int main() {
	bool all_right;
	all_right = true;
	
	vector <string> p0;
	long long p1;
	
	{
	// ----- test 0 -----
	string t0[] = {"Y","Y","Y","Y","Y","Y","Y","Y"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 0ll;
	all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 1 -----
	string t0[] = {"YNNNNNNN","NYNNNNNN","NNYNNNNN","NNNYNNNN","NNNNYNNN","NNNNNYNN","NNNNNNYN","NNNNNNNY"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 1ll;
	all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 2 -----
	string t0[] = {"YNNYN","YYYYY","NYYNY","YNYYN","YNNYY","YNNYY","NNNYY","NYYYY"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 250ll;
	all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 3 -----
	string t0[] = {"YNNYN","YYYYY","NNNNN","YNYYN","YNNYY","YNNYY","NNNYY","NYYYY"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 0ll;
	all_right = KawigiEdit_RunTest(3, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 4 -----
	string t0[] = {"YNNYNYYYYYNN","NNNYNYYNYNNY","YYNNYYNNNYYN","YYYYYNNYYYNN","NNNYYYNNYNYN","YYYNYYYYNYNN","NNNNNNYYNYYN","NNYNYYNNYNYY"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 611480ll;
	all_right = KawigiEdit_RunTest(4, p0, true, p1) && all_right;
	// ------------------
	}
	
	if (all_right) {
		cout << "You're a stud (at least on the example cases)!" << endl;
	} else {
		cout << "Some of the test cases had errors." << endl;
	}
	return 0;
}
// END KAWIGIEDIT TESTING
// Author: Shubham Gupta
//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
