#include <vector>
#include <map>
#include <queue>
#include <algorithm>
#include <sstream>
#include <iostream>
#include <cmath>
#include <cstdlib>
#include <set>
#include <numeric>

#define FOR(A,B,C) for(int A=B;A<C;A++)
#define EFOR(A,B,C) for(int A=B;A<=C;A++)
#define RFOR(A,B,C) for(int A=B;A>=C;A--)
#define PB(A,B) A.push_back(B);
#define SORT(A) sort( A.begin(),A.end() )
#define ALL(A) A.begin(),A.end()
#define VI vector<int>
#define VS vector<string>
#define VD vector<double>
#define VB vector<bool>
#define SZ(A) int(A.size())
#define LL long long

using namespace std;

class Islands {
public:
	int beachLength(vector <string>);
};

int Islands::beachLength(vector <string> kdm) {
	int R=SZ(kdm),C=SZ(kdm[0]);
	int cnt=0;

	FOR(row,0,R)
		FOR(col,0,C){

			if(col-1>=0 && kdm[row][col]=='#' && kdm[row][col-1]=='.')
				++cnt;
			if(col+1<C && kdm[row][col]=='#' && kdm[row][col+1]=='.')
				++cnt;

			if(row%2==0){
				if(row-1>=0 && col-1>=0 && kdm[row][col]=='#' && kdm[row-1][col-1]=='.')
					++cnt;
				if(row-1>=0 && kdm[row][col]=='#' && kdm[row-1][col]=='.')
					++cnt;
				if(row+1<R && col-1>=0 && kdm[row][col]=='#' && kdm[row+1][col-1]=='.')
					++cnt;
				if(row+1<R && kdm[row][col]=='#' && kdm[row+1][col]=='.')
					++cnt;
			} else {
				if(row-1>=0 && kdm[row][col]=='#' && kdm[row-1][col]=='.')
					++cnt;
				if(row-1>=0 && col+1<C && kdm[row][col]=='#' && kdm[row-1][col+1]=='.')
					++cnt;
				if(row+1<R && kdm[row][col]=='#' && kdm[row+1][col]=='.')
					++cnt;
				if(row+1<R && col+1<C && kdm[row][col]=='#' && kdm[row+1][col+1]=='.')
					++cnt;
			}
	}
	return cnt;
}
// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
bool KawigiEdit_RunTest(int testNum, vector <string> p0, bool hasAnswer, int p1) {
	cout << "Test " << testNum << ": [" << "{";
	for (int i = 0; int(p0.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << "\"" << p0[i] << "\"";
	}
	cout << "}";
	cout << "]" << endl;
	Islands *obj;
	int answer;
	obj = new Islands();
	clock_t startTime = clock();
	answer = obj->beachLength(p0);
	clock_t endTime = clock();
	delete obj;
	bool res;
	res = true;
	cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
	if (hasAnswer) {
		cout << "Desired answer:" << endl;
		cout << "\t" << p1 << endl;
	}
	cout << "Your answer:" << endl;
	cout << "\t" << answer << endl;
	if (hasAnswer) {
		res = answer == p1;
	}
	if (!res) {
		cout << "DOESN'T MATCH!!!!" << endl;
	} else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
		cout << "FAIL the timeout" << endl;
		res = false;
	} else if (hasAnswer) {
		cout << "Match :-)" << endl;
	} else {
		cout << "OK, but is it right?" << endl;
	}
	cout << "" << endl;
	return res;
}
int main() {
	bool all_right;
	all_right = true;
	
	vector <string> p0;
	int p1;
	
	{
	// ----- test 0 -----
	string t0[] = {".#...#.."};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 4;
	all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 1 -----
	string t0[] = {"..#.##",".##.#.","#.#..."};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 19;
	all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 2 -----
	string t0[] = {"#...#.....","##..#...#."};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 15;
	all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 3 -----
	string t0[] = {"....#.",".#....","..#..#","####.."};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 24;
	all_right = KawigiEdit_RunTest(3, p0, true, p1) && all_right;
	// ------------------
	}
	
	if (all_right) {
		cout << "You're a stud (at least on the example cases)!" << endl;
	} else {
		cout << "Some of the test cases had errors." << endl;
	}
	return 0;
}
// END KAWIGIEDIT TESTING
// Author: Shubham Gupta
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
